// Astro_project/frontend/src/pages/profile/profile.vue
<template>
    <v-container class="fill-height d-flex justify-center align-center">
        <v-card width="620" class="profile-card" elevation="24">
            
            <!-- BANNER SUPERIOR (LinkedIn Style) -->
            <div class="banner-section">
                <v-img src="/fondo3.jpg" cover height="180" class="banner-image">
                    <template v-slot:placeholder>
                        <div class="d-flex align-center justify-center fill-height">
                            <v-progress-circular indeterminate color="cyan"></v-progress-circular>
                        </div>
                    </template>
                </v-img>
            </div>

            <!-- CONTENIDO DE CABECERA (Overlap) -->
            <div class="profile-header-wrap px-8">
                <div class="avatar-overlap-container">
                    <!-- Avatar Principal -->
                    <div class="main-avatar-box">
                        <v-avatar size="180" class="avatar-circle">
                            <v-img :src="`/${avatar}`" alt="Avatar" cover></v-img>
                        </v-avatar>
                        <v-btn icon="mdi-camera" size="small" color="cyan-accent-3" class="btn-edit-avatar" elevation="4"
                            @click="avatarDialog = true"></v-btn>
                    </div>

                    <!-- Mascota Integrada -->
                    <div class="mascot-overlap-box">
                        <v-avatar v-if="mascot" size="85" class="mascot-badge-big" @click="mascotDialog = true">
                            <v-img :src="`/${mascot}`" cover></v-img>
                        </v-avatar>
                        <v-btn v-else icon="mdi-paw-plus" size="large" color="purple-accent-1" class="btn-add-mascot" @click="mascotDialog = true"></v-btn>
                    </div>
                </div>

                <!-- Datos del Usuario -->
                <div class="user-info-section text-left mt-4">
                    <div class="d-flex align-center justify-space-between w-100">
                        <div class="flex-grow-1 pr-6">
                            <h1 class="text-h3 font-weight-black text-white mb-0 capitalize">
                                {{ user || 'Explorador' }}
                            </h1>
                            <div class="d-flex align-center ga-2 mt-1 mb-3">
                                <v-chip color="cyan-accent-3" size="small" variant="flat" class="text-black font-weight-bold">
                                    {{ rank || 'Cadete Estelar' }}
                                </v-chip>
                                <span class="text-grey-lighten-1 text-body-2">• Nivel {{ level || 1 }}</span>
                                <div class="d-flex align-center ga-1 ml-3">
                                    <div class="status-dot-large" :class="user ? 'online' : 'offline'"></div>
                                    <span class="text-caption text-grey">{{ user ? 'En órbita' : 'En base' }}</span>
                                </div>
                            </div>
                            
                            <div class="d-flex align-center w-100 mt-2">
                                <v-progress-linear
                                    :model-value="(xp / xpRequired) * 100"
                                    color="cyan-accent-3"
                                    height="8"
                                    rounded
                                    bg-color="rgba(255,255,255,0.1)"
                                    class="mr-3 shadow-cyan"
                                ></v-progress-linear>
                                <span class="text-caption text-cyan-accent-3 font-weight-bold" style="white-space: nowrap;">
                                    {{ xp }} / {{ xpRequired }} XP
                                </span>
                            </div>
                        </div>
                        
                        <div class="text-right pl-4" style="border-left: 1px solid rgba(255,255,255,0.1);">
                            <div class="text-h3 font-weight-bold text-amber-accent-3 mb-n1">{{ coins }}</div>
                            <div class="text-caption text-grey text-uppercase tracking-wider">Monedas</div>
                        </div>
                    </div>
                </div>

                <v-divider class="my-6 border-opacity-10"></v-divider>

                <!-- Plan y Estadísticas Rápidas -->
                <div class="quick-stats d-flex justify-space-between mb-8">
                    <div class="stat-card">
                        <span class="label">PLAN ACTUAL</span>
                        <span class="value text-cyan-accent-3">{{ plan || 'INDIVIDUAL_FREE' }}</span>
                    </div>
                    <div class="stat-card text-center">
                        <span class="label">MISIÓN</span>
                        <span class="value">EXPLORACIÓN</span>
                    </div>
                    <div class="stat-card text-right">
                        <span class="label">SISTEMA</span>
                        <span class="value">ASTRO-V1</span>
                    </div>
                </div>

                <!-- Logros Seleccionados -->
                <div class="achievements-section mb-8">
                    <div class="d-flex align-center justify-space-between mb-4">
                        <h3 class="text-overline font-weight-black text-grey-lighten-1">CONDECORACIONES ACTIVAS</h3>
                        <span class="text-caption text-cyan-accent-3 cursor-pointer" @click="goToInventory">Gestionar</span>
                    </div>
                    <v-row dense>
                        <v-col v-for="i in 3" :key="i" cols="4">
                            <v-card variant="flat" color="#1a1d26" class="achievement-display-box"
                                @click="openSelection(i - 1)" height="120">
                                <Medal v-if="getAchievement(selectedAchievements[i - 1])"
                                    :type="getAchievement(selectedAchievements[i - 1]).type"
                                    :icon="getAchievement(selectedAchievements[i - 1]).icon" :scale="0.65"
                                    :icon-size="48" />
                                <v-icon v-else icon="mdi-plus" color="grey-darken-3" size="36"></v-icon>
                            </v-card>
                        </v-col>
                    </v-row>
                </div>

                <!-- Botonera Final -->
                <div class="actions-grid ga-3 mb-8">
                    <v-row dense>
                        <v-col cols="6">
                            <v-btn block color="grey-darken-4" height="48" rounded="lg" @click="goToInventory" class="font-weight-bold">
                                INVENTARIO
                            </v-btn>
                        </v-col>
                        <v-col cols="6">
                            <v-btn block color="grey-darken-4" height="48" rounded="lg" @click="changePlan" class="font-weight-bold">
                                CAMBIAR PLAN
                            </v-btn>
                        </v-col>
                    </v-row>
                    <v-btn block color="#c62828" height="48" rounded="lg" @click="handleLogout" class="font-weight-bold mt-2">
                        ABORTAR MISIÓN Y SALIR
                    </v-btn>
                </div>
            </div>
        </v-card>
        <!-- Diálogo de Selección de Logros -->
        <v-dialog v-model="selectionDialog" max-width="500">
            <v-card class="glass-popup pa-4">
                <v-card-title class="text-white font-weight-bold d-flex justify-space-between align-center">
                    Seleccionar Logro
                    <v-btn icon="mdi-close" variant="text" color="white" @click="selectionDialog = false"></v-btn>
                </v-card-title>
                <v-card-text>
                    <v-list bg-color="transparent" class="text-white">
                        <v-list-item v-for="achievement in allAchievements" :key="achievement.id"
                            :title="achievement.title" :subtitle="achievement.description"
                            @click="achievement.unlocked ? selectAchievement(achievement.id) : null"
                            :disabled="!achievement.unlocked" class="mb-2 achievement-list-item" :class="{
                                'selected': isSelected(achievement.id),
                                'locked-item': !achievement.unlocked
                            }">
                            <template v-slot:prepend>
                                <div class="mr-4 d-flex align-center justify-center"
                                    style="width: 60px; height: 60px; overflow: hidden;">
                                    <Medal :type="achievement.type" :icon="achievement.icon" :scale="0.3"
                                        :icon-size="48" :locked="!achievement.unlocked" />
                                </div>
                            </template>
                        </v-list-item>
                        <v-divider class="my-2 border-opacity-20"></v-divider>
                        <v-list-item prepend-icon="mdi-delete-outline" title="Quitar Logro"
                            @click="selectAchievement(null)" class="text-error"></v-list-item>
                    </v-list>
                </v-card-text>
            </v-card>
        </v-dialog>

        <!-- Diálogo de Selección de Avatar -->
        <v-dialog v-model="avatarDialog" max-width="500">
            <v-card class="glass-popup pa-4">
                <v-card-title class="text-white font-weight-bold d-flex justify-space-between align-center">
                    Traje de Astronauta
                    <v-btn icon="mdi-close" variant="text" color="white" @click="avatarDialog = false"></v-btn>
                </v-card-title>
                <v-card-text>
                    <v-row class="mt-2 text-center">
                        <v-col v-for="opt in avatarOptions" :key="opt.file" cols="4" sm="3" class="pa-2">
                            <v-avatar size="70" class="avatar-option" :class="{ 'active-avatar': avatar === opt.file }"
                                @click="selectAvatar(opt.file)">
                                <v-img :src="`/${opt.file}`"></v-img>
                            </v-avatar>
                            <div class="text-caption text-grey-lighten-1 mt-1">{{ opt.label }}</div>
                        </v-col>
                    </v-row>
                </v-card-text>
            </v-card>
        </v-dialog>

        <!-- Diálogo de Selección de Mascota -->
        <v-dialog v-model="mascotDialog" max-width="500">
            <v-card class="glass-popup pa-4">
                <v-card-title class="text-white font-weight-bold d-flex justify-space-between align-center">
                    Compañero de Misión
                    <v-btn icon="mdi-close" variant="text" color="white" @click="mascotDialog = false"></v-btn>
                </v-card-title>
                <v-card-text>
                    <v-row class="mt-2 text-center">
                        <v-col v-for="m in mascotOptions" :key="m.file" cols="4" sm="3" class="pa-2">
                            <v-avatar size="70" class="avatar-option" :class="{ 'active-avatar': mascot === m.file }"
                                @click="selectMascot(m.file)">
                                <v-img :src="`/${m.file}`"></v-img>
                            </v-avatar>
                            <div class="text-caption text-grey-lighten-1 mt-1">{{ m.label }}</div>
                        </v-col>
                        <v-col cols="4" sm="3" class="pa-2">
                            <v-avatar size="70" class="avatar-option d-flex align-center justify-center" @click="selectMascot(null)" style="border: 1px dashed rgba(255,255,255,0.3)">
                                <v-icon color="grey">mdi-close</v-icon>
                            </v-avatar>
                            <div class="text-caption text-grey-lighten-1 mt-1">Ninguno</div>
                        </v-col>
                    </v-row>
                </v-card-text>
            </v-card>
        </v-dialog>
    </v-container>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAstroStore } from '@/stores/astroStore' // Importamos el store
import { storeToRefs } from 'pinia' // Para mantener la reactividad
import { ACHIEVEMENTS } from '@/constants/achievements'
import Medal from '@/components/achievements/Medal.vue'

const router = useRouter()
const astroStore = useAstroStore()

const selectionDialog = ref(false)
const avatarDialog = ref(false)
const mascotDialog = ref(false)
const currentSlotIndex = ref(null)
const { user, rank, plan, selectedAchievements, avatar, mascot, level, coins, xp } = storeToRefs(astroStore)

 const xpRequired = computed(() => {
    return 100 + ((level.value || 1) - 1) * 50;
})

const avatarOptions = [
    { label: 'Blanc', file: 'Astronauta_blanc.jpg' },
    { label: 'Groc', file: 'Astronauta_groc.jpg' },
    { label: 'Lila', file: 'Astronauta_lila.jpg' },
    { label: 'Negre', file: 'Astronauta_negre.jpg' },
    { label: 'Taronja', file: 'Astronauta_taronja.jpg' },
    { label: 'Verd', file: 'Astronauta_verd.jpg' },
    { label: 'Vermell', file: 'Astronauta_vermell.jpg' }
]

const mascotOptions = [
    { label: 'Balena', file: 'Balena_alien.jpg' },
    { label: 'Alien', file: 'Mascota_alien2.jpg' },
    { label: 'Dron', file: 'Mascota_dron.jpg' },
    { label: 'Pop', file: 'Pop_alien.jpg' }
]

// Extraemos los datos del usuario de forma reactiva

// Mostramos todos los logros pero marcamos los bloqueados (Demo: 1 y 3 desbloqueados)
const allAchievements = computed(() => {
    return ACHIEVEMENTS.map(a => ({
        ...a,
        unlocked: [1, 3].includes(a.id)
    }))
})

function isSelected(id) {
    return selectedAchievements.value.some(sid => sid !== null && Number(sid) === Number(id))
}

function getAchievement(id) {
    if (id === null || id === undefined) return null
    return ACHIEVEMENTS.find(a => a.id === Number(id))
}

function openSelection(index) {
    currentSlotIndex.value = index
    selectionDialog.value = true
}

async function selectAchievement(achievementId) {
    if (!user.value) {
        console.error("❌ No se puede guardar: Usuario no identificado");
        alert("Debes iniciar sesión para guardar tus logros.");
        return;
    }

    // Cerramos el diálogo inmediatamente para mejor UX
    selectionDialog.value = false;

    // Convertimos a número si no es null
    const targetId = achievementId !== null ? Number(achievementId) : null;

    // Clonamos la selección actual
    let newSelection = [...selectedAchievements.value];

    // Si el logro ya estaba en otro slot, lo quitamos de ahí para evitar duplicados
    if (targetId !== null) {
        const existingIndex = newSelection.findIndex(id => id !== null && Number(id) === targetId);
        if (existingIndex !== -1) {
            newSelection[existingIndex] = null;
        }
    }

    // Ponemos el nuevo logro en el slot actual
    newSelection[currentSlotIndex.value] = targetId;

    // Guardamos la selección completa (la store se encarga de la actualización optimista)
    console.log(`🎯 Seleccionando logro ${targetId} para slot ${currentSlotIndex.value}`);
    const result = await astroStore.updateAchievements(newSelection);

    if (!result.success) {
        console.error("❌ Error al sincronizar con el servidor:", result.message);
    }
}

function handleLogout() {
    astroStore.logout()
    router.push('/login')
}

function changePlan() {
    router.push('/plans')
}

function goToInventory() {
    router.push('/inventory')
}

function selectAvatar(file) {
    astroStore.updateAvatar(file)
    avatarDialog.value = false
}

function selectMascot(file) {
    astroStore.updateMascot(file)
    mascotDialog.value = false
}
</script>


<style scoped>

.shadow-cyan { filter: drop-shadow(0 0 4px rgba(0, 229, 255, 0.4)); }
.tracking-wider { letter-spacing: 1px; }

/* Estilo Base */
.fill-height {
    background: url('/fondo1.jpg') center center / cover no-repeat fixed !important;
}

/* Tarjeta Principal (Sólida, no Glassmorphism) */
.profile-card {
    background: #0d0f14 !important;
    border: 1px solid rgba(255, 255, 255, 0.05);
    border-radius: 16px;
    overflow: hidden;
}

/* Banner superior */
.banner-section {
    position: relative;
    background: #1a1d26;
}

.banner-image {
    filter: brightness(0.7);
}

/* Contenedor de Avatar con Overlap */
.profile-header-wrap {
    position: relative;
    z-index: 1;
}

.avatar-overlap-container {
    position: relative;
    margin-top: -70px; /* LinkedIn Style Overlap */
    margin-bottom: 20px;
    display: flex;
    align-items: flex-end;
    gap: 15px;
}

.main-avatar-box {
    position: relative;
}

.avatar-circle {
    border: 6px solid #0d0f14;
    background: white;
    box-shadow: 0 8px 25px rgba(0,0,0,0.6);
    overflow: hidden;
    display: flex;
    align-items: center;
    justify-content: center;
}

.avatar-circle :deep(.v-img__img) {
    border-radius: 50%;
    transform: scale(1.4);
    transform-origin: center center;
    object-position: center center;
}

.btn-edit-avatar {
    position: absolute;
    bottom: 5px;
    right: 5px;
    border: 4px solid #0d0f14 !important;
    z-index: 2;
}

/* Mascota Integrada en la Cabecera */
.mascot-overlap-box {
    margin-bottom: 5px;
}

.mascot-badge-big {
    border: 5px solid #0d0f14;
    background: white;
    box-shadow: 0 4px 15px rgba(0,0,0,0.5);
    cursor: pointer;
    transition: all 0.2s ease-in-out;
}

.mascot-badge-big :deep(.v-img__img) {
    border-radius: 50%;
    transform: scale(1.4);
    transform-origin: center center;
    object-position: center center;
}

.mascot-badge-big:hover {
    transform: scale(1.1) rotate(5deg);
}

.btn-add-mascot {
    border: 3px solid #0d0f14 !important;
}

/* Datos de Usuario */
.capitalize {
    text-transform: capitalize;
}

.status-dot-large {
    width: 10px;
    height: 10px;
    border-radius: 50%;
}

.status-dot-large.online { background: #4caf50; box-shadow: 0 0 10px #4caf50; }
.status-dot-large.offline { background: #f44336; }

/* Tarjetas de Estadísticas */
.quick-stats {
    gap: 10px;
}

.stat-card {
    flex: 1;
    display: flex;
    flex-direction: column;
}

.stat-card .label {
    font-size: 10px;
    font-weight: 900;
    color: #616161;
    letter-spacing: 1px;
}

.stat-card .value {
    font-size: 14px;
    font-weight: 700;
    color: #e0e0e0;
}

/* Logros */
.achievement-display-box {
    border: 1px solid rgba(255,255,255,0.05);
    border-radius: 12px;
    cursor: pointer;
    transition: all 0.3s ease;
}

.achievement-display-box:hover {
    background: #242835 !important;
    border-color: rgba(0, 229, 255, 0.3);
    transform: translateY(-4px);
}

/* Diálogos (Sí mantenemos un poco de glass para los popups) */
.glass-popup {
    background: rgba(15, 17, 23, 0.95) !important;
    backdrop-filter: blur(20px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 20px;
}

.achievement-list-item {
    border-radius: 12px;
    margin-bottom: 8px;
    background: rgba(255,255,255,0.02);
}

.achievement-list-item:hover {
    background: rgba(255,255,255,0.05);
}

.achievement-list-item.selected {
    background: rgba(0, 229, 255, 0.1);
    border: 1px solid rgba(0, 229, 255, 0.3);
}

.avatar-option {
    cursor: pointer;
    transition: all 0.2s;
    border: 2px solid transparent;
}

.avatar-option:hover {
    transform: scale(1.1);
    border-color: #00e5ff;
}

.active-avatar {
    border-color: #00e5ff !important;
    box-shadow: 0 0 15px rgba(0, 229, 255, 0.4);
}

.locked-item {
    opacity: 0.4;
    filter: grayscale(1);
}
</style>

// Astro_project/frontend/mobile/app/(tabs)/profile.tsx
import React, { useState, useMemo } from 'react';
import {
    View,
    Text,
    StyleSheet,
    ScrollView,
    Image,
    TouchableOpacity,
    Dimensions,
    SafeAreaView,
    Modal,
    FlatList
} from 'react-native';
import { useAstroStore } from '../../stores/astroStore';
import { ACHIEVEMENTS } from '../../constants/achievements';
import Medal from '../../components/achievements/Medal';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';

const { width } = Dimensions.get('window');

const avatarOptions = [
    { label: 'Blanc', file: 'Astronauta_blanc.jpg', require: null },
    { label: 'Groc', file: 'Astronauta_groc.jpg', require: null },
    { label: 'Lila', file: 'Astronauta_lila.jpg', require: null },
    { label: 'Negre', file: 'Astronauta_negre.jpg', require: null },
    { label: 'Taronja', file: 'Astronauta_taronja.jpg', require: null },
    { label: 'Verd', file: 'Astronauta_verd.jpg', require: null },
    { label: 'Vermell', file: 'Astronauta_vermell.jpg', require: null }
];

const mascotOptions = [
    { label: 'Balena', file: 'Balena_alien.jpg', require: null },
    { label: 'Alien', file: 'Mascota_alien2.jpg', require: null },
    { label: 'Dron', file: 'Mascota_dron.jpg', require: null },
    { label: 'Pop', file: 'Pop_alien.jpg', require: null }
];

const ProfileScreen = () => {
    const router = useRouter();
    const {
        user,
        rank,
        plan,
        selectedAchievements,
        avatar,
        mascot,
        logout,
        updateAvatar,
        updateMascot,
        updateAchievements
    } = useAstroStore();

    const [avatarDialog, setAvatarDialog] = useState(false);
    const [mascotDialog, setMascotDialog] = useState(false);
    const [selectionDialog, setSelectionDialog] = useState(false);
    const [currentSlotIndex, setCurrentSlotIndex] = useState<number | null>(null);

    const getAchievement = (id: number | null) => {
        if (id === null) return null;
        return ACHIEVEMENTS.find((a: any) => a.id === id);
    };

    const currentAvatarSource = useMemo(() => {
        const option = avatarOptions.find(o => o.file === avatar);
        return option ? option.require : avatarOptions[0].require;
    }, [avatar]);

    const currentMascotSource = useMemo(() => {
        if (!mascot) return null;
        const option = mascotOptions.find(o => o.file === mascot);
        return option ? option.require : null;
    }, [mascot]);

    const handleSelectAchievement = async (achievementId: number | null) => {
        if (currentSlotIndex === null) return;

        let newSelection = [...selectedAchievements];
        // Remove duplicate if exists in another slot
        if (achievementId !== null) {
            const existingIndex = newSelection.findIndex(id => id !== null && Number(id) === achievementId);
            if (existingIndex !== -1) {
                newSelection[existingIndex] = null;
            }
        }
        newSelection[currentSlotIndex] = achievementId;

        await updateAchievements(newSelection);
        setSelectionDialog(false);
    };

    const handleLogout = () => {
        logout();
        router.replace('/');
    };

    return (
        <SafeAreaView style={styles.container}>
            <ScrollView contentContainerStyle={styles.scrollContent}>
                {/* Banner Section */}
                <View style={styles.bannerContainer}>
                    {/* Banner Image Removed */}
                    <LinearGradient
                        colors={['transparent', 'rgba(13, 15, 20, 1)']}
                        style={styles.bannerOverlay}
                    />
                </View>

                {/* Profile Header Overlap */}
                <View style={styles.headerOverlap}>
                    <View style={styles.avatarOverlapContainer}>
                        <View style={styles.mainAvatarBox}>
                            <View style={styles.avatarCircle}>
                                <Image source={currentAvatarSource} style={styles.avatarImage} />
                            </View>
                            <TouchableOpacity
                                style={styles.editAvatarBtn}
                                onPress={() => setAvatarDialog(true)}
                            >
                                <MaterialCommunityIcons name="camera" size={20} color="#00e5ff" />
                            </TouchableOpacity>
                        </View>

                        <View style={styles.mascotOverlapBox}>
                            {currentMascotSource ? (
                                <TouchableOpacity onPress={() => setMascotDialog(true)}>
                                    <View style={styles.mascotBadgeBig}>
                                        <Image source={currentMascotSource} style={styles.mascotImage} />
                                    </View>
                                </TouchableOpacity>
                            ) : (
                                <TouchableOpacity
                                    style={styles.btnAddMascot}
                                    onPress={() => setMascotDialog(true)}
                                >
                                    <MaterialCommunityIcons name="paw" size={24} color="#7000ff" />
                                </TouchableOpacity>
                            )}
                        </View>
                    </View>
                </View>

                {/* User Info Section */}
                <View style={styles.userInfo}>
                    <Text style={styles.userName}>{user || 'Explorador'}</Text>
                    <View style={styles.rankRow}>
                        <View style={styles.rankChip}>
                            <Text style={styles.rankText}>{rank || 'Cadete Estelar'}</Text>
                        </View>
                        <Text style={styles.levelText}>• Nivel 1</Text>
                        <View style={[styles.statusDot, user ? styles.online : styles.offline]} />
                        <Text style={styles.statusText}>{user ? 'En órbita' : 'En base'}</Text>
                    </View>
                </View>

                <View style={styles.divider} />

                {/* Quick Stats */}
                <View style={styles.statsRow}>
                    <View style={styles.statItem}>
                        <Text style={styles.statLabel}>PLAN ACTUAL</Text>
                        <Text style={[styles.statValue, { color: '#00e5ff' }]}>{plan || 'INDIVIDUAL_FREE'}</Text>
                    </View>
                    <View style={styles.statItem}>
                        <Text style={styles.statLabel}>MISIÓN</Text>
                        <Text style={styles.statValue}>EXPLORACIÓN</Text>
                    </View>
                    <View style={styles.statItem}>
                        <Text style={styles.statLabel}>SISTEMA</Text>
                        <Text style={styles.statValue}>ASTRO-V1</Text>
                    </View>
                </View>

                {/* Achievements Section */}
                <View style={styles.achievementsHeader}>
                    <Text style={styles.sectionTitle}>LOGROS ACTIVOS</Text>
                    <TouchableOpacity onPress={() => router.push('/achievements')}>
                        <Text style={styles.viewMoreText}>VER TODOS</Text>
                    </TouchableOpacity>
                </View>
                <View style={styles.achievementsRow}>
                    {selectedAchievements.map((id: number | null, index: number) => {
                        const achievement = getAchievement(id);
                        return (
                            <TouchableOpacity
                                key={index}
                                style={styles.achievementBox}
                                onPress={() => {
                                    setCurrentSlotIndex(index);
                                    setSelectionDialog(true);
                                }}
                            >
                                {achievement ? (
                                    <Medal
                                        type={achievement.type as any}
                                        icon={achievement.icon}
                                        scale={0.5}
                                        iconSize={48}
                                    />
                                ) : (
                                    <MaterialCommunityIcons name="plus" size={32} color="#424242" />
                                )}
                            </TouchableOpacity>
                        );
                    })}
                </View>

                {/* Actions Grid */}
                <View style={styles.actionsGrid}>
                    <View style={styles.buttonRow}>
                        <TouchableOpacity style={styles.actionBtn} onPress={() => router.push('/inventory')}>
                            <Text style={styles.btnText}>INVENTARIO</Text>
                        </TouchableOpacity>
                        <TouchableOpacity style={styles.actionBtn} onPress={() => router.push('/plans')}>
                            <Text style={styles.btnText}>CAMBIAR PLAN</Text>
                        </TouchableOpacity>
                    </View>
                    <TouchableOpacity
                        style={[styles.actionBtn, styles.logoutBtn]}
                        onPress={handleLogout}
                    >
                        <Text style={styles.btnText}>CERRAR SESIÓN Y SALIR</Text>
                    </TouchableOpacity>
                </View>
            </ScrollView>

            {/* Dialogs */}
            <SelectionModal
                visible={avatarDialog}
                onClose={() => setAvatarDialog(false)}
                title="Traje de Astronauta"
                data={avatarOptions}
                current={avatar}
                onSelect={(file: string) => {
                    updateAvatar(file);
                    setAvatarDialog(false);
                }}
            />

            <SelectionModal
                visible={mascotDialog}
                onClose={() => setMascotDialog(false)}
                title="Compañero de Misión"
                data={mascotOptions}
                current={mascot}
                onSelect={(file: string | null) => {
                    updateMascot(file);
                    setMascotDialog(false);
                }}
                allowNone
            />

            {/* Achievement Selection Modal */}
            <Modal visible={selectionDialog} transparent animationType="fade">
                <View style={styles.modalOverlay}>
                    <View style={styles.modalContent}>
                        <View style={styles.modalHeader}>
                            <Text style={styles.modalTitle}>Seleccionar Logro</Text>
                            <TouchableOpacity onPress={() => setSelectionDialog(false)}>
                                <MaterialCommunityIcons name="close" size={24} color="white" />
                            </TouchableOpacity>
                        </View>
                        <FlatList
                            data={ACHIEVEMENTS}
                            keyExtractor={(item) => item.id.toString()}
                            renderItem={({ item }) => {
                                const isSelected = selectedAchievements.includes(item.id);
                                return (
                                    <TouchableOpacity
                                        style={[styles.achievementListItem, isSelected && styles.selectedItem]}
                                        onPress={() => handleSelectAchievement(item.id)}
                                    >
                                        <View style={styles.medalSmall}>
                                            <Medal type={item.type as any} icon={item.icon} scale={0.3} iconSize={48} />
                                        </View>
                                        <View style={styles.achievementInfo}>
                                            <Text style={styles.achievementTitle}>{item.title}</Text>
                                            <Text style={styles.achievementDesc}>{item.description}</Text>
                                        </View>
                                    </TouchableOpacity>
                                );
                            }}
                            ListFooterComponent={
                                <TouchableOpacity
                                    style={styles.achievementListItem}
                                    onPress={() => handleSelectAchievement(null)}
                                >
                                    <MaterialCommunityIcons name="delete-outline" size={24} color="#ef4444" />
                                    <Text style={[styles.achievementTitle, { color: '#ef4444', marginLeft: 12 }]}>Quitar Logro</Text>
                                </TouchableOpacity>
                            }
                        />
                    </View>
                </View>
            </Modal>
        </SafeAreaView>
    );
};

const SelectionModal = ({ visible, onClose, title, data, current, onSelect, allowNone = false }: any) => (
    <Modal visible={visible} transparent animationType="slide">
        <View style={styles.modalOverlay}>
            <View style={styles.modalContent}>
                <View style={styles.modalHeader}>
                    <Text style={styles.modalTitle}>{title}</Text>
                    <TouchableOpacity onPress={onClose}>
                        <MaterialCommunityIcons name="close" size={24} color="white" />
                    </TouchableOpacity>
                </View>
                <View style={styles.grid}>
                    {data.map((item: any) => (
                        <TouchableOpacity
                            key={item.file}
                            style={styles.gridItem}
                            onPress={() => onSelect(item.file)}
                        >
                            <View style={[styles.optionCircle, current === item.file && styles.activeOption]}>
                                <Image source={item.require} style={styles.optionImage} />
                            </View>
                            <Text style={styles.optionLabel}>{item.label}</Text>
                        </TouchableOpacity>
                    ))}
                    {allowNone && (
                        <TouchableOpacity
                            style={styles.gridItem}
                            onPress={() => onSelect(null)}
                        >
                            <View style={[styles.optionCircle, styles.noneCircle, current === null && styles.activeOption]}>
                                <MaterialCommunityIcons name="close" size={32} color="#616161" />
                            </View>
                            <Text style={styles.optionLabel}>Ninguno</Text>
                        </TouchableOpacity>
                    )}
                </View>
            </View>
        </View>
    </Modal>
);

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000000',
    },
    scrollContent: {
        paddingBottom: 40,
    },
    bannerContainer: {
        height: 180,
        width: '100%',
        backgroundColor: '#1a1d26',
    },
    bannerImage: {
        width: '100%',
        height: '100%',
        opacity: 0.6,
    },
    bannerOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 100,
    },
    headerOverlap: {
        marginTop: -70,
        paddingHorizontal: 24,
    },
    avatarOverlapContainer: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 16,
    },
    mainAvatarBox: {
        position: 'relative',
    },
    avatarCircle: {
        width: 140,
        height: 140,
        borderRadius: 70,
        borderWidth: 6,
        borderColor: '#0d0f14',
        backgroundColor: 'white',
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarImage: {
        width: '140%',
        height: '140%',
    },
    editAvatarBtn: {
        position: 'absolute',
        bottom: 5,
        right: 5,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#1a1d26',
        borderWidth: 3,
        borderColor: '#0d0f14',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 4,
    },
    mascotOverlapBox: {
        marginBottom: 5,
    },
    mascotBadgeBig: {
        width: 80,
        height: 80,
        borderRadius: 40,
        borderWidth: 5,
        borderColor: '#0d0f14',
        backgroundColor: 'white',
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    mascotImage: {
        width: '140%',
        height: '140%',
    },
    btnAddMascot: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: 'rgba(112, 0, 255, 0.1)',
        borderWidth: 2,
        borderColor: '#0d0f14',
        justifyContent: 'center',
        alignItems: 'center',
    },
    userInfo: {
        paddingHorizontal: 24,
        marginTop: 16,
    },
    userName: {
        fontSize: 32,
        fontWeight: '900',
        color: 'white',
        textTransform: 'capitalize',
    },
    rankRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        gap: 8,
    },
    rankChip: {
        backgroundColor: '#00e5ff',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    rankText: {
        color: 'black',
        fontSize: 12,
        fontWeight: 'bold',
    },
    levelText: {
        color: '#bdbdbd',
        fontSize: 12,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginLeft: 4,
    },
    online: {
        backgroundColor: '#4caf50',
    },
    offline: {
        backgroundColor: '#f44336',
    },
    statusText: {
        color: '#757575',
        fontSize: 12,
    },
    divider: {
        height: 1,
        backgroundColor: 'rgba(255,255,255,0.05)',
        marginHorizontal: 24,
        marginVertical: 24,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        marginBottom: 32,
    },
    statItem: {
        flex: 1,
    },
    statLabel: {
        fontSize: 10,
        fontWeight: '900',
        color: '#616161',
        letterSpacing: 1,
    },
    statValue: {
        fontSize: 14,
        fontWeight: '700',
        color: '#e0e0e0',
        marginTop: 4,
    },
    sectionTitle: {
        fontSize: 12,
        fontWeight: '900',
        color: '#bdbdbd',
        letterSpacing: 1,
    },
    viewMoreText: {
        color: '#00e5ff',
        fontSize: 10,
        fontWeight: 'bold',
    },
    achievementsHeader: {
        paddingHorizontal: 24,
        marginBottom: 16,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    achievementsRow: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        gap: 10,
        marginBottom: 32,
    },
    achievementBox: {
        flex: 1,
        height: 120,
        backgroundColor: '#1a1d26',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    actionsGrid: {
        paddingHorizontal: 24,
        gap: 12,
    },
    buttonRow: {
        flexDirection: 'row',
        gap: 12,
    },
    actionBtn: {
        flex: 1,
        height: 48,
        backgroundColor: '#1a1b1e',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    logoutBtn: {
        backgroundColor: '#c62828',
        marginTop: 8,
    },
    btnText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 14,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.85)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#0d0f14',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        maxHeight: '80%',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 16,
    },
    gridItem: {
        width: (width - 80) / 3,
        alignItems: 'center',
        marginBottom: 16,
    },
    optionCircle: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: 'white',
        overflow: 'hidden',
        borderWidth: 3,
        borderColor: 'transparent',
    },
    activeOption: {
        borderColor: '#00e5ff',
    },
    optionImage: {
        width: '100%',
        height: '100%',
    },
    optionLabel: {
        color: '#bdbdbd',
        fontSize: 12,
        marginTop: 8,
        textAlign: 'center',
    },
    noneCircle: {
        backgroundColor: '#1a1d26',
        justifyContent: 'center',
        alignItems: 'center',
    },
    achievementListItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: 'rgba(255,255,255,0.02)',
        borderRadius: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    selectedItem: {
        borderColor: '#00e5ff30',
        backgroundColor: 'rgba(0, 229, 255, 0.05)',
    },
    medalSmall: {
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    achievementInfo: {
        flex: 1,
        marginLeft: 16,
    },
    achievementTitle: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    achievementDesc: {
        color: '#757575',
        fontSize: 12,
        marginTop: 2,
    }
});

export default ProfileScreen;
