// Astro_project/frontend/web/src/pages/auth/register.vue
<template>
  <v-container fluid class="fill-height register-container d-flex align-center justify-center">
    <div class="stars-overlay"></div>
    
    <v-card
      elevation="24"
      max-width="500"
      width="100%"
      class="pa-8 register-card glass-panel"
    >
      <div class="d-flex justify-start mb-4">
        <v-btn
          variant="text"
          density="compact"
          color="cyan-lighten-3"
          class="back-btn-tech"
          @click="router.push('/')"
        >
          <v-icon start size="small">mdi-chevron-left</v-icon>
          <span class="text-caption font-weight-bold">ABORTAR / VOLVER A BASE</span>
        </v-btn>
      </div>

      <div class="text-center mb-8 header-section">
        <div class="hologram-effect mb-4">
          <v-icon color="cyan-accent-3" size="64" class="pulse-icon">mdi-shield-account-outline</v-icon>
        </div>
        <h1 class="text-h3 font-weight-black text-white tracking-widest neon-text mb-2">
          ALISTAMIENTO
        </h1>
        <div class="text-overline text-cyan-lighten-3 tracking-wide border-bottom-pulse">
          NUEVO TRIPULANTE ASTRO
        </div>
      </div>

      <v-form ref="registerForm" @submit.prevent="handleRegister">
        <v-row dense>
          <v-col cols="12">
            <div class="text-caption text-cyan-lighten-4 mb-1 ml-1 font-weight-bold">IDENTIFICACIÓN</div>
            <v-text-field
              v-model="formData.username"
              placeholder="NOMBRE DE USUARIO (TU ID)"
              variant="solo-filled"
              bg-color="rgba(0, 20, 40, 0.6)"
              prepend-inner-icon="mdi-account-box-outline"
              color="cyan-accent-3"
              class="future-input"
              :rules="[v => !!v || 'ID Requerido']"
              hide-details="auto"
            ></v-text-field>
            <div class="text-caption text-grey-lighten-1 mt-1 ml-1 font-italic">
              *Este será tu nombre visible en la misión
            </div>
          </v-col>

          <v-col cols="12" sm="6" class="mt-4">
            <div class="text-caption text-cyan-lighten-4 mb-1 ml-1 font-weight-bold">CREDENCIALES</div>
            <v-text-field
              v-model="formData.password"
              placeholder="CONTRASEÑA"
              type="password"
              variant="solo-filled"
              bg-color="rgba(0, 20, 40, 0.6)"
              prepend-inner-icon="mdi-lock-outline"
              color="cyan-accent-3"
              class="future-input"
              :rules="[v => !!v || 'Código Requerido']"
              hide-details="auto"
            ></v-text-field>
          </v-col>

          <v-col cols="12" sm="6" class="mt-4">
            <div class="text-caption text-cyan-lighten-4 mb-1 ml-1 font-weight-bold">VERIFICACIÓN</div>
            <v-text-field
              v-model="formData.confirmPassword"
              placeholder="CONFIRMAR CONTRASEÑA"
              type="password"
              variant="solo-filled"
              bg-color="rgba(0, 20, 40, 0.6)"
              prepend-inner-icon="mdi-lock-check-outline"
              color="cyan-accent-3"
              class="future-input"
              :error-messages="passwordMatchError"
              hide-details="auto"
            ></v-text-field>
          </v-col>
        </v-row>

        <div v-if="errorMessage" class="error-display mt-6 pa-3 d-flex align-center">
          <v-icon color="red-accent-2" class="mr-3">mdi-alert-octagon</v-icon>
          <span class="text-red-lighten-1 font-weight-bold">{{ errorMessage }}</span>
        </div>

        <v-btn
          block
          height="64"
          color="cyan-accent-3"
          type="submit"
          class="register-btn font-weight-black mt-8 text-h6"
          :loading="loading"
          :disabled="!!passwordMatchError"
        >
          <v-icon start class="mr-2">mdi-rocket-launch</v-icon>
          INICIAR PROTOCOLO DE ALTA
          <div class="btn-glow"></div>
        </v-btn>
      </v-form>

      <div class="d-flex justify-space-between align-center mt-8 pt-4 border-top-tech">
        <div class="text-caption text-grey-lighten-1 cursor-pointer hover-bright" @click="router.push('/login')">
          <v-icon size="small" class="mr-1">mdi-login</v-icon> 
          ¿YA TIENES ID? ACCEDER
        </div>
        <div class="coordinate-display text-body-2 font-weight-bold text-cyan-lighten-4 font-weight-mono">
          COORDENADAS: <span class="text-cyan-accent-2 glow-text">SECTOR-7G</span>
        </div>
      </div>
    </v-card>
  </v-container>
</template>

<script setup>
import { ref, computed } from 'vue';
import { useRouter } from 'vue-router';
import { useAstroStore } from '@/stores/astroStore';

const router = useRouter();
const astroStore = useAstroStore();

const loading = ref(false);
const errorMessage = ref('');

const formData = ref({
  username: '',
  password: '',
  confirmPassword: ''
});

const passwordMatchError = computed(() => {
  if (!formData.value.confirmPassword) return '';
  return formData.value.password !== formData.value.confirmPassword 
    ? 'Los códigos no coinciden' 
    : '';
});

const handleRegister = async () => {
    if (passwordMatchError.value) return;
    if (!formData.value.username || !formData.value.password) {
        errorMessage.value = "Todos los campos son obligatorios.";
        return;
    }
    
    loading.value = true;
    errorMessage.value = '';

    try {
        const tripulanteData = {
            username: formData.value.username,
            password: formData.value.password,
        };

        const result = await astroStore.registerTripulante(tripulanteData);
        
        if (result.success) {
            router.push('/login'); 
        } else {
            errorMessage.value = result.message || "Error al procesar el alta.";
        }
        
    } catch (err) {
        errorMessage.value = "Error crítico: No se ha podido contactar con la base.";
    } finally {
        loading.value = false;
    }
};
</script>

<style scoped>
/* Container & Background */
.register-container {
  background: radial-gradient(circle at center, #0b1021 0%, #000000 100%);
  position: relative;
  overflow: hidden;
}

.stars-overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: 
    radial-gradient(white 1px, transparent 1px),
    radial-gradient(rgba(255, 255, 255, 0.5) 2px, transparent 2px);
  background-size: 50px 50px, 150px 150px;
  background-position: 0 0, 40px 60px;
  opacity: 0.2;
  animation: starMove 100s linear infinite;
}

@keyframes starMove {
  from { transform: translateY(0); }
  to { transform: translateY(-1000px); }
}

/* Glass Card */
.glass-panel {
  background: rgba(10, 25, 41, 0.75) !important;
  backdrop-filter: blur(12px);
  border: 1px solid rgba(0, 242, 255, 0.15);
  box-shadow: 0 0 40px rgba(0, 0, 0, 0.6), inset 0 0 20px rgba(0, 242, 255, 0.05) !important;
  border-radius: 4px;
  position: relative;
  overflow: hidden;
}

/* Header Elements */
.neon-text {
  text-shadow: 0 0 10px rgba(0, 242, 255, 0.5), 0 0 20px rgba(0, 242, 255, 0.3);
  font-family: 'Roboto Mono', monospace;
  letter-spacing: 0.15em !important;
}

.border-bottom-pulse {
  border-bottom: 2px solid rgba(0, 242, 255, 0.3);
  display: inline-block;
  padding-bottom: 4px;
}

.pulse-icon {
  animation: pulse 3s infinite;
}

@keyframes pulse {
  0% { text-shadow: 0 0 0 rgba(0, 242, 255, 0.4); }
  50% { text-shadow: 0 0 20px rgba(0, 242, 255, 0.8); }
  100% { text-shadow: 0 0 0 rgba(0, 242, 255, 0.4); }
}

/* Inputs */
.future-input :deep(.v-field) {
  border-radius: 0;
  border: 1px solid rgba(0, 242, 255, 0.2);
  transition: all 0.3s ease;
}

.future-input :deep(.v-field--focused) {
  border-color: #00f2ff;
  box-shadow: 0 0 15px rgba(0, 242, 255, 0.2);
}

.future-input :deep(input) {
  font-family: 'Roboto Mono', monospace;
  letter-spacing: 1px;
  color: white !important;
}

/* Button */
.register-btn {
  border-radius: 2px;
  position: relative;
  overflow: hidden;
  transition: all 0.3s;
  letter-spacing: 2px;
  background: linear-gradient(90deg, rgba(0,242,255,0.8) 0%, rgba(0,180,255,0.8) 100%) !important;
}

.register-btn:hover {
  transform: scale(1.02);
  box-shadow: 0 0 30px rgba(0, 242, 255, 0.4);
}

.btn-glow {
  position: absolute;
  top: -50%;
  left: -50%;
  width: 200%;
  height: 200%;
  background: radial-gradient(circle, rgba(255,255,255,0.3) 0%, transparent 60%);
  transform: rotate(45deg);
  animation: shine 3s infinite;
}

@keyframes shine {
  0% { transform: translateX(-150%) rotate(45deg); }
  100% { transform: translateX(150%) rotate(45deg); }
}

/* Error Display */
.error-display {
  background: rgba(255, 0, 0, 0.1);
  border: 1px solid rgba(255, 0, 0, 0.3);
  border-left: 4px solid #ff4081;
}

/* Footer Tech Details */
.border-top-tech {
  border-top: 1px dashed rgba(255, 255, 255, 0.1);
}

.font-weight-mono {
  font-family: 'Roboto Mono', monospace;
}

.glow-text {
  text-shadow: 0 0 8px rgba(0, 242, 255, 0.8);
}

.hover-bright {
  transition: color 0.3s;
}
.hover-bright:hover {
  color: white !important;
}

:deep(.v-field__input) {
    color: white !important;
}
</style>

// Astro_project/frontend/mobile/app/register.tsx
import React, { useState } from 'react';
import {
    View,
    Text,
    StyleSheet,
    TextInput,
    TouchableOpacity,
    SafeAreaView,
    ActivityIndicator,
    KeyboardAvoidingView,
    Platform,
    ScrollView
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useAstroStore } from '../stores/astroStore';

export default function RegisterScreen() {
    const router = useRouter();
    const { registerTripulante } = useAstroStore();

    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    const handleRegister = async () => {
        if (!username || !password || !confirmPassword) {
            setError('Todos los campos son obligatorios');
            return;
        }

        if (password !== confirmPassword) {
            setError('Los códigos no coinciden');
            return;
        }

        setLoading(true);
        setError('');

        try {
            const result = await registerTripulante({ username, password });
            if (result.success) {
                router.replace('/login');
            } else {
                setError(result.message || 'Error al procesar el alta');
            }
        } catch (e) {
            setError('Error crítico: No se ha podido contactar con la base');
        } finally {
            setLoading(false);
        }
    };

    return (
        <SafeAreaView style={styles.container}>
            <KeyboardAvoidingView
                behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
                style={{ flex: 1 }}
            >
                <ScrollView contentContainerStyle={styles.scrollContent}>
                    <TouchableOpacity
                        style={styles.backButton}
                        onPress={() => router.back()}
                    >
                        <MaterialCommunityIcons name="chevron-left" size={24} color="#00e5ff" />
                        <Text style={styles.backButtonText}>ABORTAR / VOLVER A BASE</Text>
                    </TouchableOpacity>

                    <View style={styles.content}>
                        <View style={styles.header}>
                            <MaterialCommunityIcons name="shield-account-outline" size={64} color="#00e5ff" />
                            <Text style={styles.logoTitle}>ALISTAMIENTO</Text>
                            <View style={styles.headerBadge}>
                                <Text style={styles.badgeText}>NUEVO TRIPULANTE ASTRO</Text>
                            </View>
                        </View>

                        <View style={styles.form}>
                            <View style={styles.inputGroup}>
                                <Text style={styles.inputLabel}>IDENTIFICACIÓN</Text>
                                <View style={styles.inputWrapper}>
                                    <MaterialCommunityIcons name="account-box-outline" size={20} color="#00e5ff" style={styles.inputIcon} />
                                    <TextInput
                                        style={styles.input}
                                        placeholder="NOMBRE DE USUARIO (TU ID)"
                                        placeholderTextColor="#475569"
                                        value={username}
                                        onChangeText={setUsername}
                                        autoCapitalize="none"
                                    />
                                </View>
                                <Text style={styles.helperText}>*Este será tu nombre visible en la misión</Text>
                            </View>

                            <View style={styles.inputGroup}>
                                <Text style={styles.inputLabel}>CREDENCIALES</Text>
                                <View style={styles.inputWrapper}>
                                    <MaterialCommunityIcons name="lock-outline" size={20} color="#00e5ff" style={styles.inputIcon} />
                                    <TextInput
                                        style={styles.input}
                                        placeholder="CONTRASEÑA"
                                        placeholderTextColor="#475569"
                                        value={password}
                                        onChangeText={setPassword}
                                        secureTextEntry
                                    />
                                </View>
                            </View>

                            <View style={styles.inputGroup}>
                                <Text style={styles.inputLabel}>VERIFICACIÓN</Text>
                                <View style={styles.inputWrapper}>
                                    <MaterialCommunityIcons name="lock-check-outline" size={20} color="#00e5ff" style={styles.inputIcon} />
                                    <TextInput
                                        style={styles.input}
                                        placeholder="CONFIRMAR CONTRASEÑA"
                                        placeholderTextColor="#475569"
                                        value={confirmPassword}
                                        onChangeText={setConfirmPassword}
                                        secureTextEntry
                                    />
                                </View>
                            </View>

                            {error ? (
                                <View style={styles.errorBox}>
                                    <MaterialCommunityIcons name="alert-octagon" size={20} color="#ef4444" />
                                    <Text style={styles.errorText}>{error}</Text>
                                </View>
                            ) : null}

                            <TouchableOpacity
                                style={styles.registerButton}
                                onPress={handleRegister}
                                disabled={loading}
                            >
                                <LinearGradient
                                    colors={['#00f2ff', '#00b4ff']}
                                    start={{ x: 0, y: 0 }}
                                    end={{ x: 1, y: 0 }}
                                    style={styles.registerGradient}
                                >
                                    {loading ? (
                                        <ActivityIndicator color="white" />
                                    ) : (
                                        <>
                                            <MaterialCommunityIcons name="rocket-launch" size={20} color="black" style={{ marginRight: 10 }} />
                                            <Text style={styles.registerButtonText}>INICIAR PROTOCOLO DE ALTA</Text>
                                        </>
                                    )}
                                </LinearGradient>
                            </TouchableOpacity>
                        </View>

                        <View style={styles.footer}>
                            <TouchableOpacity onPress={() => router.push('/login')}>
                                <Text style={styles.footerLink}>¿YA TIENES ID? ACCEDER</Text>
                            </TouchableOpacity>
                            <Text style={styles.coordText}>COORDENADAS: <Text style={styles.coordValue}>SECTOR-7G</Text></Text>
                        </View>
                    </View>
                </ScrollView>
            </KeyboardAvoidingView>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    scrollContent: {
        flexGrow: 1,
        padding: 24,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 30,
    },
    backButtonText: {
        color: '#00e5ff',
        fontSize: 12,
        fontWeight: 'bold',
        marginLeft: 4,
    },
    content: {
        flex: 1,
        justifyContent: 'center',
    },
    header: {
        alignItems: 'center',
        marginBottom: 30,
    },
    logoTitle: {
        fontSize: 36,
        fontWeight: '900',
        color: 'white',
        letterSpacing: 4,
        marginTop: 10,
    },
    headerBadge: {
        borderBottomWidth: 2,
        borderBottomColor: 'rgba(0, 229, 255, 0.3)',
        paddingBottom: 4,
        marginTop: 8,
    },
    badgeText: {
        color: '#00e5ff',
        fontSize: 10,
        fontWeight: 'bold',
        letterSpacing: 2,
    },
    form: {
        gap: 16,
    },
    inputGroup: {
        gap: 6,
    },
    inputLabel: {
        color: '#94a3b8',
        fontSize: 12,
        fontWeight: 'bold',
        marginLeft: 4,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 20, 40, 0.6)',
        borderWidth: 1,
        borderColor: 'rgba(0, 229, 255, 0.2)',
        height: 56,
        paddingHorizontal: 16,
    },
    inputIcon: {
        marginRight: 12,
    },
    input: {
        flex: 1,
        color: 'white',
        fontSize: 16,
        fontWeight: '500',
    },
    helperText: {
        color: '#64748b',
        fontSize: 10,
        fontStyle: 'italic',
        marginLeft: 4,
    },
    errorBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(239, 68, 68, 0.3)',
        borderLeftWidth: 4,
        borderLeftColor: '#ef4444',
        padding: 12,
        marginTop: 8,
    },
    errorText: {
        color: '#f87171',
        fontWeight: 'bold',
        marginLeft: 10,
    },
    registerButton: {
        height: 64,
        marginTop: 20,
        overflow: 'hidden',
    },
    registerGradient: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    registerButtonText: {
        color: 'black',
        fontSize: 16,
        fontWeight: '900',
        letterSpacing: 1,
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 30,
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
        borderStyle: 'dashed',
    },
    footerLink: {
        color: '#94a3b8',
        fontSize: 12,
        fontWeight: 'bold',
    },
    coordText: {
        color: '#94a3b8',
        fontSize: 12,
        fontWeight: 'bold',
    },
    coordValue: {
        color: '#00e5ff',
    },
});
