// Astro_project/frontend/mobile/components/achievements/Medal.tsx
import React from 'react';
import { View, StyleSheet } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons } from '@expo/vector-icons';

interface MedalProps {
    type: 'gold' | 'silver' | 'bronze';
    icon: string;
    locked?: boolean;
    scale?: number;
    iconSize?: number;
}

const Medal: React.FC<MedalProps> = ({
    type = 'bronze',
    icon = 'star',
    locked = false,
    scale = 1,
    iconSize = 48
}) => {
    const gradients = {
        gold: ['#ffd700', '#b8860b'],
        silver: ['#e0e0e0', '#757575'],
        bronze: ['#cd7f32', '#8b4513'],
    };

    const ribbonGradients = {
        gold: ['#d32f2f', '#b71c1c'],
        silver: ['#1976d2', '#0d47a1'],
        bronze: ['#388e3c', '#1b5e20'],
    };

    const ribbonBorder = {
        gold: '#ffeb3b',
        silver: '#90caf9',
        bronze: '#a5d6a7',
    };

    return (
        <View style={[
            styles.container,
            { transform: [{ scale }] },
            locked && styles.locked
        ]}>
            {/* Ribbon */}
            <View style={styles.ribbonWrapper}>
                <LinearGradient
                    colors={ribbonGradients[type] as any}
                    style={[styles.ribbon, { borderTopColor: ribbonBorder[type] }]}
                />
            </View>

            {/* Medal Body */}
            <LinearGradient
                colors={gradients[type] as any}
                style={styles.medalBody}
            >
                <LinearGradient
                    colors={['rgba(255, 255, 255, 0.4)', 'transparent', 'rgba(255, 255, 255, 0.1)'] as any}
                    style={styles.shine}
                />
                <View style={styles.content}>
                    <MaterialCommunityIcons
                        name={locked ? 'lock' : (icon as any)}
                        size={iconSize}
                        color={locked ? '#e0e0e0' : 'white'}
                    />
                </View>
                <View style={styles.border} />
            </LinearGradient>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        width: 140,
        height: 180,
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingTop: 40,
    },
    locked: {
        opacity: 0.6,
    },
    ribbonWrapper: {
        position: 'absolute',
        top: 0,
        width: 60,
        height: 100,
        zIndex: 1,
        overflow: 'hidden',
    },
    ribbon: {
        width: '100%',
        height: '100%',
        borderTopWidth: 5,
    },
    medalBody: {
        width: 140,
        height: 140,
        borderRadius: 70,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.4,
        shadowRadius: 20,
    },
    shine: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: 70,
        zIndex: 4,
    },
    content: {
        zIndex: 3,
    },
    border: {
        position: 'absolute',
        top: -5,
        left: -5,
        right: -5,
        bottom: -5,
        borderRadius: 75,
        borderWidth: 4,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
});

export default Medal;

// Astro_project/frontend/src/components/achievements/Medal.vue
<template>
  <div :class="['medal-container', { 'locked': locked }]" :style="{ transform: `scale(${scale})` }">
    <!-- Ribbon -->
    <div :class="['ribbon', type]"></div>

    <!-- Medal Body -->
    <div :class="['medal-body', type]">
      <div class="medal-shine"></div>
      <div class="medal-content d-flex flex-column align-center justify-center">
        <v-icon :icon="locked ? 'mdi-lock' : icon" :size="iconSize"
          :color="locked ? 'grey-lighten-2' : 'white'"></v-icon>
      </div>
      <div class="medal-border"></div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  type: {
    type: String,
    default: 'bronze'
  },
  icon: {
    type: String,
    default: 'mdi-star'
  },
  locked: {
    type: Boolean,
    default: false
  },
  scale: {
    type: Number,
    default: 1
  },
  iconSize: {
    type: Number,
    default: 48
  }
})
</script>

<style scoped>
.medal-container {
  width: 140px;
  height: 140px;
  cursor: default;
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  transform-origin: center center;
}

.medal-container.locked {
  filter: grayscale(1) brightness(0.7);
  opacity: 0.6;
}

/* Medal Body */
.medal-body {
  width: 140px;
  height: 140px;
  border-radius: 50%;
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.4), inset 0 0 20px rgba(255, 255, 255, 0.2);
  z-index: 2;
}

.medal-content {
  width: 100%;
  height: 100%;
  border-radius: 50%;
  z-index: 3;
}

.medal-border {
  position: absolute;
  top: -5px;
  left: -5px;
  right: -5px;
  bottom: -5px;
  border-radius: 50%;
  border: 4px solid rgba(255, 255, 255, 0.2);
  pointer-events: none;
}

/* Metallic Gradients */
.gold {
  background: radial-gradient(circle at 30% 30%, #ffd700, #b8860b 80%);
  border: 1px solid #ffec8b;
}

.silver {
  background: radial-gradient(circle at 30% 30%, #e0e0e0, #757575 80%);
  border: 1px solid #ffffff;
}

.bronze {
  background: radial-gradient(circle at 30% 30%, #cd7f32, #8b4513 80%);
  border: 1px solid #ffa07a;
}

/* Ribbon */
.ribbon {
  position: absolute;
  top: -40px;
  left: 50%;
  transform: translateX(-50%);
  width: 60px;
  height: 100px;
  z-index: 1;
  clip-path: polygon(0% 0%, 100% 0%, 100% 100%, 50% 80%, 0% 100%);
}

.ribbon.gold {
  background: linear-gradient(to bottom, #d32f2f, #b71c1c);
  border-top: 5px solid #ffeb3b;
}

.ribbon.silver {
  background: linear-gradient(to bottom, #1976d2, #0d47a1);
  border-top: 5px solid #90caf9;
}

.ribbon.bronze {
  background: linear-gradient(to bottom, #388e3c, #1b5e20);
  border-top: 5px solid #a5d6a7;
}

/* Shine Effect */
.medal-shine {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  border-radius: 50%;
  background: linear-gradient(135deg, rgba(255, 255, 255, 0.4) 0%, transparent 50%, rgba(255, 255, 255, 0.1) 100%);
  pointer-events: none;
  z-index: 4;
}
</style>
